# Default values for angular-node-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 10

image:
  repository: webappdemo.azurecr.io/webappdemo/web-app:v1
  pullPolicy: Always

application:
  name: webapp